org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = com.polypheides
mod_id = resolutionscaler
mod_name = Polypheides Resolution Scaler
mod_version = 1.2.4+mc26.4
mod_file_name = resolutionscaler-fabric

minecraft_version = 26.4-snapshot-1
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.1+26.4

# Modrinth Publishing
# Put your Modrinth Project ID here (from the Modrinth website)
MODRINTH_PROJECT_ID = qjx7H5d3
